Finished support for tomcat6, need to debug
git-svn-id: http://debian-tomcat-scripts.googlecode.com/svn/trunk@13 7589a92b-d149-0410-8731-cd42004992f6

diff --git a/multiple-instances/init.d/tomcat6 b/multiple-instances/init.d/tomcat6
--- a/multiple-instances/init.d/tomcat6
+++ b/multiple-instances/init.d/tomcat6
@@ -1,10 +1,11 @@
 #!/bin/sh
 #
-# /etc/init.d/tomcat5.5 -- startup script for the Tomcat 5 servlet engine
+# /etc/init.d/tomcat6 -- startup script for the Tomcat 6 servlet engine
 #
 # Written by Miquel van Smoorenburg <miquels@cistron.nl>.
 # Modified for Debian GNU/Linux	by Ian Murdock <imurdock@gnu.ai.mit.edu>.
 # Modified for Tomcat by Stefan Gybas <sgybas@debian.org>.
+# Modified for Tomcat6 by Thierry Carrez <thierry.carrez@ubuntu.com>.
 #
 ### BEGIN INIT INFO
 # Provides:          tomcat
@@ -21,33 +22,60 @@
 set -e
 
 PATH=/bin:/usr/bin:/sbin:/usr/sbin
-NAME=tomcat5.5
+NAME=tomcat6
 DESC="Tomcat servlet engine"
 DAEMON=/usr/bin/jsvc
 CATALINA_HOME=/usr/share/$NAME
 HOST_NAME=@HOST_NAME@
 DEFAULT=/etc/default/$NAME/instances/$HOST_NAME
+JVM_TMP=/tmp/tomcat6-temp
+
+if [ `id -u` -ne 0 ]; then
+	echo "You need root privileges to run this script"
+	exit 1
+fi
+ 
+# Make sure tomcat is started with system locale
+if [ -r /etc/default/locale ]; then
+	. /etc/default/locale
+	export LANG
+fi
 
 . /lib/lsb/init-functions
 . /etc/default/rcS
 
+
 # The following variables can be overwritten in $DEFAULT
 
-# Run Tomcat 5 as this user ID
-TOMCAT5_USER=tomcat55
+# Run Tomcat 6 as this user ID
+TOMCAT6_USER=tomcat6
 
 # The first existing directory is used for JAVA_HOME (if JAVA_HOME is not
 # defined in $DEFAULT)
-JDK_DIRS="/usr/lib/jvm/java-6-openjdk /usr/lib/jvm/java-6-sun /usr/lib/jvm/java-1.5.0-sun /usr/lib/j2sdk1.4-sun /usr/lib/j2sdk1.4-blackdown /usr/lib/j2se/1.4 /usr/lib/j2sdk1.5-sun /usr/lib/j2sdk1.3-sun /usr/lib/j2sdk1.3-blackdown /usr/lib/j2sdk1.5-ibm /usr/lib/j2sdk1.4-ibm /usr/lib/jvm/java-gcj /usr/lib/kaffe"
+JDK_DIRS="/usr/lib/jvm/java-6-openjdk /usr/lib/jvm/java-6-sun /usr/lib/jvm/java-1.5.0-sun /usr/lib/j2sdk1.5-sun /usr/lib/j2sdk1.5-ibm"
+
+# Look for the right JVM to use
+for jdir in $JDK_DIRS; do
+    if [ -r "$jdir/bin/java" -a -z "${JAVA_HOME}" ]; then
+	JAVA_HOME="$jdir"
+    fi
+done
+export JAVA_HOME
 
 # Directory for per-instance configuration files and webapps
-CATALINA_BASE=/var/lib/tomcat5.5/instances/$HOST_NAME
+CATALINA_BASE=/var/lib/tomcat6/instances/$HOST_NAME
 
 # Use the Java security manager? (yes/no)
-TOMCAT5_SECURITY=no
+TOMCAT6_SECURITY=no
 
-# Timeout in seconds for the shutdown of all webapps
-TOMCAT5_SHUTDOWN=30
+# Default Java options
+# Set java.awt.headless=true if JAVA_OPTS is not set so the
+# Xalan XSL transformer can work without X11 display on JDK 1.4+
+# It also looks like the default heap size of 64M is not enough for most cases
+# so the maximum heap size is set to 128M
+if [ -z "$JAVA_OPTS" ]; then
+	JAVA_OPTS="-Djava.awt.headless=true -Xmx128M"
+fi
 
 # End of variables that can be overwritten in $DEFAULT
 
@@ -56,47 +84,32 @@ if [ -f "$DEFAULT" ]; then
 	. "$DEFAULT"
 fi
 
-test -f $DAEMON || exit 0
-
-[ -z "$TOMCAT5_USER" ] && TOMCAT5_USER=tomcat55
-
-# Look for the right JVM to use
-for jdir in $JDK_DIRS; do
-	if [ -r "$jdir/bin/java" -a -z "${JAVA_HOME}" ]; then
-		JAVA_HOME_TMP="$jdir"
-		# checks for a real JDK like environment, needed to check if 
-		# really the java-gcj-compat-dev package is installed
-		if [ -r "$jdir/bin/jdb" ]; then
-			JAVA_HOME="$JAVA_HOME_TMP"
-		fi
-	fi
-done
-export JAVA_HOME
-
-# Set java.awt.headless=true if JAVA_OPTS is not set so the
-# Xalan XSL transformer can work without X11 display on JDK 1.4+
-# It also looks like the default heap size of 64M is not enough for most cases
-# se the maximum heap size is set to 128M
-if [ -z "$JAVA_OPTS" ]; then
-	JAVA_OPTS="-Djava.awt.headless=true -Xmx128M"
+if [ ! -f "$CATALINA_HOME/bin/bootstrap.jar" ]; then
+	log_failure_msg "$NAME is not installed"
+	exit 1
 fi
 
-JAVA_OPTS="$JAVA_OPTS -Djava.endorsed.dirs=$CATALINA_HOME/common/endorsed -Dcatalina.base=$CATALINA_BASE -Dcatalina.home=$CATALINA_HOME -Djava.io.tmpdir=$CATALINA_BASE/temp"
+if [ ! -f "$DAEMON" ]; then
+	log_failure_msg "missing $DAEMON"
+	exit 1
+fi
 
-# Set the JSP compiler if set in the tomcat5.5.default file
+POLICY_CACHE="$CATALINA_BASE/work/catalina.policy"
+
+JAVA_OPTS="$JAVA_OPTS -Djava.endorsed.dirs=$CATALINA_HOME/endorsed -Dcatalina.base=$CATALINA_BASE -Dcatalina.home=$CATALINA_HOME -Djava.io.tmpdir=$JVM_TMP"
+
+# Set the JSP compiler if set in the tomcat6.default file
 if [ -n "$JSP_COMPILER" ]; then
 	JAVA_OPTS="$JAVA_OPTS -Dbuild.compiler=$JSP_COMPILER"
 fi
 
-if [ "$TOMCAT5_SECURITY" = "yes" ]; then
-	JAVA_OPTS="$JAVA_OPTS -Djava.security.manager -Djava.security.policy=$CATALINA_BASE/conf/catalina.policy"
+if [ "$TOMCAT6_SECURITY" = "yes" ]; then
+	JAVA_OPTS="$JAVA_OPTS -Djava.security.manager -Djava.security.policy=$POLICY_CACHE"
 fi
 
-# juli LogManager disabled if running under libgcj (see bug #395167)
-gcj=no
-"$JAVA_HOME/bin/java" -version 2>&1 | grep -q "^gij (GNU libgcj)" && gcj=yes
-if [ "$gcj" != "yes" ]; then
-  JAVA_OPTS="$JAVA_OPTS -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.util.logging.config.file=$CATALINA_BASE/conf/logging.properties"
+# Set juli LogManager if logging.properties is provided
+if [ -r "$CATALINA_BASE"/conf/logging.properties ]; then
+  JAVA_OPTS="$JAVA_OPTS "-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager" "-Djava.util.logging.config.file="$CATALINA_BASE/conf/logging.properties"
 fi
 
 # Define other required variables
@@ -119,63 +132,73 @@ case "$1" in
 	fi
 
 	if [ ! -d "$CATALINA_BASE/conf" ]; then
-		log_failure_msg "invalid CATALINA_BASE specified"
+		log_failure_msg "invalid CATALINA_BASE: $CATALINA_BASE"
 		exit 1
 	fi
 
 	log_daemon_msg "Starting $DESC" "$NAME"
 	if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
-		--user $TOMCAT5_USER --startas "$JAVA_HOME/bin/java" \
+		--user $TOMCAT6_USER --startas "$JAVA_HOME/bin/java" \
 		>/dev/null; then
 
-		# Clean up and set permissions on required files
-		rm -rf "$CATALINA_BASE"/temp/*
-		chown --dereference "$TOMCAT5_USER" "$CATALINA_BASE/conf" \
-			"$CATALINA_BASE/conf/tomcat-users.xml" \
-			"$CATALINA_BASE/logs" "$CATALINA_BASE/temp" \
-			"$CATALINA_BASE/webapps" "$CATALINA_BASE/work" \
-			"$CATALINA_BASE/logs/catalina.out" || true
+		# Remove / recreate JVM_TMP directory
+		rm -rf "$JVM_TMP"
+		mkdir "$JVM_TMP" || {
+			log_failure_msg "could not create JVM temporary directory"
+			exit 1
+		}
+		chown $TOMCAT6_USER "$JVM_TMP"
+		cd "$JVM_TMP"
 
-		$DAEMON -user "$TOMCAT5_USER" -cp "$JSVC_CLASSPATH" \
+		$DAEMON -user "$TOMCAT6_USER" -cp "$JSVC_CLASSPATH" \
 		    -outfile "$LOGFILE"  -errfile '&1' \
 		    -pidfile "$CATALINA_PID" $JAVA_OPTS "$BOOTSTRAP_CLASS"
+
+		sleep 5
+        	if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
+			--user $TOMCAT6_USER --startas "$JAVA_HOME/bin/java" \
+			>/dev/null; then
+			log_end_msg 1
+		else
+			log_end_msg 0
+		fi
 	else
 	        log_progress_msg "(already running)"
+		log_end_msg 0
 	fi
-	log_end_msg 0
 	;;
   stop)
 	log_daemon_msg "Stopping $DESC" "$NAME"
         if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
-		--user "$TOMCAT5_USER" --startas "$JAVA_HOME/bin/java" \
+		--user "$TOMCAT6_USER" --startas "$JAVA_HOME/bin/java" \
 		>/dev/null; then
 		log_progress_msg "(not running)"
 	else
 		$DAEMON -cp "$JSVC_CLASSPATH" -pidfile "$CATALINA_PID" \
 		     -stop "$BOOTSTRAP_CLASS"
 	fi
+	rm -rf "$JVM_TMP"
 	log_end_msg 0
 	;;
    status)
         if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
-		--user $TOMCAT5_USER --startas "$JAVA_HOME/bin/java" \
+		--user $TOMCAT6_USER --startas "$JAVA_HOME/bin/java" \
 		>/dev/null; then
 
 		if [ -f "$CATALINA_PID" ]; then
 		    log_success_msg "$DESC is not running, but pid file exists."
-		    exit 1
+			exit 1
 		else
 		    log_success_msg "$DESC is not running."
-		    exit 3
+			exit 3
 		fi
 	else
 		log_success_msg "$DESC is running with pid `cat $CATALINA_PID`"
-		exit 0
 	fi
         ;;
   restart|force-reload)
         if start-stop-daemon --test --stop --pidfile "$CATALINA_PID" \
-		--user $TOMCAT5_USER --startas "$JAVA_HOME/bin/java" \
+		--user $TOMCAT6_USER --startas "$JAVA_HOME/bin/java" \
 		>/dev/null; then
 		$0 stop
 		sleep 1
@@ -184,7 +207,7 @@ case "$1" in
 	;;
   try-restart)
         if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
-		--user $TOMCAT5_USER --startas "$JAVA_HOME/bin/java" \
+		--user $TOMCAT6_USER --startas "$JAVA_HOME/bin/java" \
 		>/dev/null; then
 		$0 start
 	fi
